; Programmable CDI Web Controller V1
; Target: Wemos D1 Mini (ESP8266)
[env:d1_mini]
platform = espressif8266
board = d1
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
board_build.filesystem = littlefs
